# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-20 19:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fotoservico',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor_base',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'BRL'))]),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor_base_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3),
        ),
    ]
