# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhodeservicos',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='carrinhodeservicos',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Estado'),
        ),
    ]
