# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200509_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionaldeservico',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriadeservico',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fotoservico',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servico',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
