# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-20 19:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200520_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionaldeservico',
            name='valor_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='carrinhodeservicos',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='carrinhodeservicos',
            name='valor_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='valor_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='adicionaldeservico',
            name='valor',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'BRL'))]),
        ),
        migrations.AlterField(
            model_name='carrinhodeservicos',
            name='subtotal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'BRL'))]),
        ),
        migrations.AlterField(
            model_name='carrinhodeservicos',
            name='valor_total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'BRL'))]),
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='valor_total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'BRL'))]),
        ),
    ]
