# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-28 14:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200528_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratodeservico',
            name='is_avaliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comentarioservico',
            name='avaliacao',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
