# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200528_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('profissional_dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profissional')),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interesses',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('ABERTO', 'ABERTO'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('REJEITADO', 'REJEITADO'), ('REALIZADO', 'REALIZADO')], default='ABERTO', max_length=100, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Interesse')),
                ('profissional_dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional_dono', to='app.Profissional')),
                ('profissional_socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional_socio', to='app.Profissional')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processo',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Interesse')),
                ('profissional_socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profissional')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Proposta',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Proposta'),
        ),
    ]
