# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-14 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200509_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fotoservico',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
