# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200529_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(blank=True, choices=[('ACEITO', 'ACEITO'), ('REJEITADO', 'REJEITADO'), ('AGUARDANDO', 'AGUARDANDO')], default='AGUARDANDO', max_length=300, null=True),
        ),
    ]
