# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-14 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200514_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhodeservicos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
