# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200529_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='telefone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='telefone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, choices=[('AGUARDANDO PAGAMENTO', 'AGUARDANDO PAGAMENTO'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('REJEITADO', 'REJEITADO'), ('REALIZADO', 'REALIZADO')], default='AGUARDANDO PAGAMENTO', max_length=100, null=True),
        ),
    ]
