# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carrinhodeservicos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratodeservico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
        migrations.AddField(
            model_name='contratodeservico',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profissional'),
        ),
    ]
