# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-30 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200530_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
