# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-24 20:31
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contratodeservico_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=300)),
                ('valor_de_desconto_currency', djmoney.models.fields.CurrencyField(choices=[(b'BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3)),
                ('valor_de_desconto', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'BRL'))])),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
            },
        ),
        migrations.CreateModel(
            name='ItemCupom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cupom')),
            ],
            options={
                'verbose_name': 'Item de Cupom',
                'verbose_name_plural': 'Itens de Cupom',
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='receber_pelo_sistema',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cupom',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profissional'),
        ),
        migrations.AddField(
            model_name='contratodeservico',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ItemCupom'),
        ),
    ]
