# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-18 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200514_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoservico',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
