# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-01 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200530_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, choices=[('AGUARDANDO PAGAMENTO', 'AGUARDANDO PAGAMENTO'), ('ABERTO', 'ABERTO'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('REJEITADO', 'REJEITADO'), ('REALIZADO', 'REALIZADO')], default='AGUARDANDO PAGAMENTO', max_length=100, null=True),
        ),
    ]
