# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200524_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
