# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200518_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioservico',
            name='avaliacao',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
