# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comentarioservico_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioservico',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
