# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cupom_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratodeservico',
            name='cupom',
        ),
        migrations.AddField(
            model_name='carrinhodeservicos',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ItemCupom'),
        ),
    ]
