# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comentarioservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioservico',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
