# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-25 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200524_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratodeservico',
            name='status',
            field=models.CharField(blank=True, choices=[('ABERTO', 'ABERTO'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('REJEITADO', 'REJEITADO'), ('REALIZADO', 'REALIZADO')], default='ABERTO', max_length=100, null=True),
        ),
    ]
