# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_emailoutelegramaadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mensagem Geral do Sistema',
                'verbose_name_plural': 'Mensagens Gerais do sistema',
            },
        ),
    ]
