# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_generalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='valor_a_combinar',
            field=models.BooleanField(default=False),
        ),
    ]
