# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-27 15:04
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200526_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('valor_currency', djmoney.models.fields.CurrencyField(choices=[(b'BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3)),
                ('valor', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'BRL'))])),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.DateField()),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO'), ('BOLETO', 'BOLETO'), ('DINHEIRO', 'DINHEIRO'), ('CHEQUE', 'CHEQUE'), ('DEBITO', 'DEBITO')], max_length=300, null=True, verbose_name='Tipo de Pagamento')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('valor_currency', djmoney.models.fields.CurrencyField(choices=[(b'BRL', 'Brazilian Real')], default='XYZ', editable=False, max_length=3)),
                ('valor', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'BRL'))])),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.DateField()),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO'), ('BOLETO', 'BOLETO'), ('DINHEIRO', 'DINHEIRO'), ('CHEQUE', 'CHEQUE'), ('DEBITO', 'DEBITO')], max_length=300, null=True, verbose_name='Tipo de Pagamento')),
            ],
            options={
                'verbose_name': 'Saida',
                'verbose_name_plural': 'Saidas',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saida',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
        migrations.AddField(
            model_name='saida',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profissional'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profissional'),
        ),
    ]
