# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200519_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadeprofissional',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
