# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200527_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cliente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='cliente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
